SharkyTheKing/Sharky

- .gitignore
- sharkymod/sharkymod.py
- silence/__init__.py
- silence/info.json
- silence/mute.py
> Publishing and addition

- lockdown/__init__.py
- lockdown/core.py
- lockdown/info.json
I will be continuously working on this, per -> https://github.com/SharkyTheKing/Sharky/issues/26. Though I wanted to get this out and onto my repo.
> [LockDown] Publish Lockdown

- reports/__init__.py
- reports/core.py
- reports/info.json
I had one of these before, I still plan on updating this but this is the basic of basics in terms of what I have planned. I hope those who use this enjoy it.
> [Reports] Publish Cog

- announcements/__init__.py
- announcements/announcements.py
- charlimit/__init__.py
- charlimit/charlimit.py
- lockdown/__init__.py
- lockdown/core.py
- newspublish/__init__.py
- newspublish/core.py
- reports/__init__.py
- reports/core.py
- sharkytools/__init__.py
- sharkytools/core.py
- strawpoll/__init__.py
- strawpoll/core.py
- verify/__init__.py
- verify/verification.py
Clarifies that none of my cog/codes contain or saves data onto the bot regarding Users.
> [Data] Clarify cog's datas

- verify/verification.py
Command name change is all that was done.
> [Verify] renaming accept to agree

- charlimit/charlimit.py
- namegen/core.py
- reports/core.py
- sharkytools/core.py
- verify/verification.py
https://cogboard.red/t/sharky-cogs/725/3
> [Approval] Commented by reviewer

- lockdown/core.py
Per https://github.com/SharkyTheKing/Sharky/issues/42
Massive rewrite to make this cleaner and better efficient.
> [Lockdown] Massive Rewrite

- charlimit/info.json
- lockdown/info.json
- namegen/info.json
- newspublish/info.json
- reports/info.json
- sharkytools/info.json
- strawpoll/info.json
- verify/info.json
> [TrustyIGotYou] Add names and install in info

- charlimit/__init__.py
- charlimit/charlimit.py
- lockdown/core.py
- namegen/core.py
- reports/core.py
- sharkytools/core.py
- strawpoll/core.py
- verify/verification.py
This fix some unused code and useless things that are not necessary or deprecated.
> Some cleanup changes.

- strawpoll/core.py
Adding guildcheck to prevent dm usage.
> [Strawpoll] Add guild check

- lockdown/core.py
Adjusted pagify: Changed from chan usage to page.
Adjusted TODO list to start focusing on new tasks.
> [Lockdown] Fix pagify and adjust todo list

- verify/info.json
@Predeactor This is for you, I forgot to tell you you should add yourself as author, you helped rewrite this based off of what I had and you did a wonderful job. Thank you and you deserve this. I'll def have to get your permissions later to update licenses later though! Thanks man,.
> [Co-Author] Adding Co-authers

- verify/verification.py
Fix a little mistake I made, GG me.
> Avoid multiple config update

- .github/workflows/lint_python.yaml
- .github/workflows/style.yaml
- lockdown/core.py
- verify/verification.py
Updating flake8, black and isort properly.
> [Format/Linting] Proper Updates

- newspublish/core.py
Cause I forgot to do this during cog creation.
> [NewsPublish] Add docstring

- reports/core.py
> [Reports] Formatting fix

- reports/core.py
This isn't finished yet, as I'm still going to be taking feedback from a specific user.
I still need to add cog disable system in here before I go forward with merge.
> [Reports] Reports Claimed

- charlimit/charlimit.py
- lockdown/core.py
- namegen/core.py
- newspublish/core.py
- reports/core.py
- sharkytools/core.py
- strawpoll/core.py
- verify/verification.py
Add version and author attributes, as well as the `format_help_for_context` function.
> [All Cogs] Version Attributes

- newspublish/core.py
Per an internal request on one of my moderated servers, it was asked to adjust logging types. I decided to go further on it and expand the loggings available.
* Changed logging information to include guild id
* Changed fail logging to be enabled
* Added success logging
> [NewsPublish] Moar Logs!

- newspublish/core.py
Haven't tested, but this should work :P
> [NewsPublish] Add blacklist feature to listener

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Add more info in readme and issue templates.
> [README] Update information

- README.md
- morseshark/__init__.py
- morseshark/core.py
- morseshark/info.json
A new cog that allows you to encode or decode morse code.
Commands:
* morse: Default command group
* encode: A subcommand of morse. Allows you to encode text into morse code.
* decode: A subcommand of morse. Allows you to decode morse code into readable text.
Currently this only works for English standard characters. I will be planning on adding future morse codes or languages in the future.
> [MorseShark] A simple morse encoder/decoder cog

- sharkytools/info.json
You can still use this cog, though I have a few ideas I would like to add onto this. 
I have zero time lately with other projects, so I decided to hide this.
> [SharkyTools] Add hidden bool

- README.md
- mailsystem/__init__.py
- mailsystem/embedmodel.py
- mailsystem/info.json
- mailsystem/mail_logic.py
- mailsystem/modmail.py
- mailsystem/settings.py
- mailsystem/usercommands.py
Thank you to @Kreusada for helping me with the code and @Flame442 for the README wording.
This is the pre-release for MailSystem, this is not completed as there's a lot that needs to be handled still.
Once this is merged, I will be listing a ton of issues that needs to be focused on. Please work with me or Kreusada in [my cog support channel](https://discord.gg/GET4DVk) before submitting a PR.
> [MailSystem] Pre-Release MailSystem

- mailsystem/mixins.py
- mailsystem/modmail.py
- mailsystem/settings.py
- mailsystem/usercommands.py
We can worry about splitting files further at another time if needbe, but here's a start. 👍
> [MailSystem] v.0.0.2 Use ABC for command classes

- README.md
> [Reports] Add `[p]reportdm` command to readme docs

- reports/core.py
Also a minor adjustment to the code quality.
> [Reports] Fix exceptions when the author cannot be DMed in `[p]reportdm` command

- mailsystem/embedmodel.py
- mailsystem/modmail.py
> [MailSystem] Fix variable name

- msgtracker/core.py
Forgot to add a try/except handling on a fetch.
> [MsgTracker] Add try and except handling

- mailsystem/modmail.py
> [MailSystem] Change get_cog to ctx.cog

- verify/verification.py
data["autoroles"] is a list so counting for none will never return 2.
Tested - it works
> [Verify] Fix check for no settings
